site: Blog
url: 
author: Elgrove
author:
  name: Elgrove
  email: 
  url: github/elgrove
  avatar: 
title: Blog
description: Blog made with colorie theme + some changes
logo: 
image: 
twitter:   
twitter:
  username: 
  creator: 
  card: 
social:
  name: 
  links:

  
permalink: pretty


baseurl:             ""

include:
  - _redirects
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  projects:
    output: true
    permalink: /projects/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"     
      
  - scope:
      path: "assets/images"
    values:
      image: true

paginate: 10
paginate_path: "/blog/page:num/"
